version: '3.1'

services:
  portainer:
    image: portainer/portainer-ce
    restart: unless-stopped
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/docker-persist/portainer-ce:/data
    networks:
      - reverse-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.wainwright.lan`)"
      - "traefik.http.routers.portainer.entrypoints=web"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "traefik.http.routers.portainer.service=portainer"
    environment:
      - VIRTUAL_HOST=portainer.wainwright.lan,portainer
      - VIRTUAL_PORT=9000    

networks:
  reverse-proxy:
    external:
      name: reverse-proxy

