version: "3"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=501
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /mnt/nfs/jellyfin/config:/config
      - /mnt/nfs/Media:/media
    network_mode: host
    restart: unless-stopped

