version: '3.1'

services:
  plex:
    image: plexinc/pms-docker
    restart: unless-stopped
    container_name: plex
    volumes:
      - /mnt/storage1/docker-persist/plex_library:/config
      - /mnt/storage1:/data
    networks:
      - reverse-proxy
    environment:
      - VIRTUAL_HOST=plex.local,plex
      - VIRTUAL_PORT=32400
      - TZ="Europe/London"
      - ADVERTISE_IP="http://192.168.221.11:32400/"
      - PLEX_UID=`id -u`
      - PLEX_GID=`id -g`
    ports:
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410-32414:32410-32414/udp

networks:
  reverse-proxy:
    external:
      name: reverse-proxy

