version: '3.1'

services:
  guacd:
    container_name: guacd_compose
    image: guacamole/guacd
    networks:
        guacnetwork_compose:
    restart: always
    volumes:
      - /mnt/storage1/docker-persist/guacamole/drive:/drive:rw
      - /mnt/storage1/docker-persist/guacamole/record:/record:rw

  postgres:
    container_name: postgres_guacamole_compose
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD: ChooseYourOwnPasswordHere1234
      POSTGRES_USER: guacamole_user
    image: postgres:13.4
    networks:
      guacnetwork_compose:
    restart: always
    volumes:
      - /mnt/storage1/docker-persist/guacamole/init:/docker-entrypoint-initdb.d:ro
      - /mnt/storage1/docker-persist/guacamole/data:/var/lib/postgresql/data:rw

  guacamole:
    container_name: guacamole_compose
    depends_on:
      - guacd
      - postgres
    environment:
      - VIRTUAL_HOST=desktop.wainwright.lan,desktop
      - VIRTUAL_PORT=8080
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - GUACD_HOSTNAME=guacd
      - POSTGRES_DATABASE=guacamole_db
      - POSTGRES_HOSTNAME=postgres
      - POSTGRES_PASSWORD=ChooseYourOwnPasswordHere1234
      - POSTGRES_USER=guacamole_user
    image: guacamole/guacamole
    links:
      - guacd
    networks:
      guacnetwork_compose:
      reverse-proxy: {}
    ports:
      - 8080:8080/tcp # Guacamole is on :8080/guacamole, not /.
    restart: always

networks:
  guacnetwork_compose:
    driver: bridge
  reverse-proxy:
    external:
      name: reverse-proxy
