version: '3.1'

services:
  mqtt:
    image: eclipse-mosquitto:latest
    restart: unless-stopped
    container_name: mqtt
    volumes:
      - /mnt/storage1/docker-persist/mqtt/config:/mosquitto/config
      - /mnt/storage1/docker-persist/mqtt/data:/mosquitto/data
      - /mnt/storage1/docker-persist/mqtt/log:/mosquitto/log
    ports:
      - 1883:1883/tcp
      - 1883:1883/udp
      - 9001:9001/tcp
      - 9001:9001/udp
