version: '3.1'

services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    volumes:
      - /mnt/storage1/docker-persist/pihole/:/etc/pihole/
      - /mnt/storage1/docker-persist/pihole/dnsmasq.d/:/etc/dnsmasq.d/
    ports:
      - '53:53/tcp'
      - '53:53/udp'
    environment:
      - ServerIP=192.168.221.11
      - PROXY_LOCATION=pihole
      - VIRTUAL_HOST=pi-hole.local,pi.hole
      - TZ=Europe/London
      - WEBPASSWORD=mypassword
    networks:
      - reverse-proxy

networks:
  reverse-proxy:
    external:
      name: reverse-proxy
