version: '3.1'

services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    volumes:
      - /mnt/storage1/docker-persist/pi-hole/:/etc/pihole/
      - /mnt/storage1/docker-persist/pi-hole/dnsmasq.d/:/etc/dnsmasq.d/
    ports:
      - 53:53/tcp
      - 53:53/udp 
    environment:
      - VIRTUAL_HOST=pi-hole.wainwright.lan,pi-hole
      - DNSMASQ_LISTENING=all
      - TZ=Europe/London
      - WEBPASSWORD=get_your_own_password
      dns:
        - 127.0.0.1
        - 1.1.1.1
    networks:
      backend:
        ipv4_address: '172.31.0.100'
      reverse-proxy: {}
    depends_on:
      - dhcphelper

  dhcphelper:
    build: ./dhcp-helper
    restart: unless-stopped
    network_mode: "host"
    command: -s 172.31.0.100
    cap_add:
      - NET_ADMIN

networks:
  backend:
    ipam:
      config:
        - subnet: 172.31.0.0/16
  reverse-proxy:
    external:
      name: reverse-proxy
