version: '3.1'

services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    volumes:
      - /mnt/storage1/docker-persist/pi-hole/:/etc/pihole/
      - /mnt/storage1/docker-persist/pi-hole/dnsmasq.d/:/etc/dnsmasq.d/
    ports:
      - 53:53/tcp
      - 53:53/udp 
    environment:
      - VIRTUAL_HOST=pi-hole.wainwright.lan,pi-hole
      - DNSMASQ_LISTENING=all
      - TZ=Europe/London
      - WEBPASSWORD=get_your_own_password
      - DNS1='10.0.0.2#5053'
      - DNS2=''
      - IPv6=false
    networks:
      backend:
        ipv4_address: '172.31.0.100'
      reverse-proxy: {}
      pihole_net:
        ipv4_address: 10.0.0.3
    depends_on:
      - dhcphelper
      - cloudflared

  cloudflared:
    container_name: cloudflared
    build:
      context: ./DoHttps
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      pihole_net:
        ipv4_address: 10.0.0.2

  dhcphelper:
    build: ./dhcp-helper
    restart: unless-stopped
    network_mode: "host"
    command: -s 172.31.0.100
    cap_add:
      - NET_ADMIN

networks:
  backend:
    ipam:
      config:
        - subnet: 172.31.0.0/16
  pihole_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/29
  reverse-proxy:
    external:
      name: reverse-proxy
