version: '3.1'

services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    volumes:
      - /mnt/storage1/docker-persist/pi-hole/:/etc/pihole/
      - /mnt/storage1/docker-persist/pi-hole/dnsmasq.d/:/etc/dnsmasq.d/
    ports:
      - 53:53/tcp
      - 53:53/udp 
    environment:
      - VIRTUAL_HOST=pi-hole.wainwright.lan,pi-hole
      - DNSMASQ_LISTENING=all
      - TZ=Europe/London
      - WEBPASSWORD=get_your_own_password      
      - DNS1='172.31.0.67#5053'
      - DNS2=''
      - IPv6=false
    networks:
      dhcp_relay:
        ipv4_address: '172.31.0.2'
      reverse-proxy: {}
      cloudflared_net:
        ipv4_address: '172.31.0.66'
    depends_on:
      - dhcphelper

  cloudflared:
    container_name: cloudflared
    build:
      context: ./DoHttps
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      cloudflared_net:
        ipv4_address: '172.31.0.67'

  dhcphelper:
    build: ./dhcp-helper
    restart: unless-stopped
    network_mode: "host"
    command: -s 172.31.0.2
    cap_add:
      - NET_ADMIN

networks:
  dhcp_relay:
    ipam:
      config:
        - subnet: 172.31.0.0/29
  cloudflared_net:
    driver: bridge
    ipam:
     config:
       - subnet: 172.31.0.64/29        
  reverse-proxy:
    external:
      name: reverse-proxy