version: '3.3'

services:
  portainer:
    image: "traefik:v2.6"
    restart: unless-stopped
    container_name: "traefik"
    ports:
      - "80:80"
      - "8080:8080"
      - "8081:8081"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.ws.address=:8081"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - reverse-proxy

networks:
  reverse-proxy:
    external:
      name: reverse-proxy

