version: '3.1'

services:
  portainer:
    image: portainer/portainer-ce
    restart: unless-stopped
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/docker-persist/portainer-ce:/data
    ports:
      - 9000:9000/tcp
    environment:
      - VIRTUAL_HOST=portainer.wainwright.lan,portainer
      - VIRTUAL_PORT=9000    
