services:
  notebook:
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    restart: unless-stopped
    ports:
      - "8888:8888"
    volumes:
      - ${NOTEBOOK_FOLDER}:/home/jovyan/notebooks
      - ./config/jupyter-config.json:/home/jovyan/.jupyter/jupyter_notebook_config.json
      - ./config:/home/jovyan/.jupyter/config
    environment:
      - VIRTUAL_HOST=jupyter.wainwright.lan,jupyter
      - VIRTUAL_PORT=8888
      - GRANT_SUDO=yes
      - NB_UID=${UID}
      - NB_GID=${GID}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jupyter.rule=Host(`jupyter.wainwright.lan`)"
      - "traefik.http.routers.jupyter.rule=Host(`jupyter`)"
      - "traefik.http.routers.jupyter.entrypoints=web"
      - "traefik.http.services.jupyter.loadbalancer.server.port=8888"
      - "traefik.http.routers.jupyter.service=jupyter"
