version: '3.1'

services:
  tvheadend:
    image: ghcr.io/linuxserver/tvheadend
    restart: unless-stopped
    container_name: tvheadend
    pid: host
    volumes:
      - /mnt/storage1/docker-persist/tvheadend:/config
      - /mnt/storage1/DVR:/recordings
    environment:
      - VIRTUAL_HOST=tvheadend.wainwright.lan,tvheadend
      - VIRTUAL_PORT=61208
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    ports:
      - 9981:9981
      - 9982:9982
    networks:
      tvheadend_net:
        ipv4_address: 192.168.221.32

networks:
  tvheadend_net:
    external: true
