version: '3.1'

services:
  nginx-rtmp:
    image: tiangolo/nginx-rtmp
    restart: unless-stopped
    container_name: nginx-rtmp
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    ports:
      - 1935:1935
