version: '3.1'

services:
  dlna:
    image: vladgh/minidlna
    container_name: minidlna
    restart: unless-stopped
    volumes:
      - /mnt/nfs/Media/Video:/media/Video
    network_mode: host
    environment:
      MINIDLNA_MEDIA_DIR: V,/media/Video
      MINIDLNA_FRIENDLY_NAME: rknas
    healthcheck:
      test: bash -c "[ -d /media/Video/Films ]"
      interval: 60s
      retries: 3
      start_period: 10s
      timeout: 3s
