version: '3.1'

services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    volumes:
      - /mnt/storage1/docker-persist/pi-hole/:/etc/pihole/
      - /mnt/storage1/docker-persist/pi-hole/dnsmasq.d/:/etc/dnsmasq.d/
    environment:
      - VIRTUAL_HOST=pi-hole.wainwright.lan,pi-hole
      - DNSMASQ_LISTENING=all
      - TZ=Europe/London
      - WEBPASSWORD=${PASSWORD}    
      - DNS1=172.31.0.67#5053
      - DNS2=
      - IPv6=false
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pi-hole.rule=Host(`pi-hole.wainwright.lan`)"
      - "traefik.http.routers.pi-hole.entrypoints=web"
      - "traefik.http.services.pi-hole.loadbalancer.server.port=80"
      - "traefik.http.routers.pi-hole.service=pi-hole"
    networks:
      reverse-proxy: {}
      cloudflared_net:
        ipv4_address: '172.31.0.66'

  cloudflared:
    container_name: cloudflared
    build:
      context: ./DoHttps
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      cloudflared_net:
        ipv4_address: '172.31.0.67'

networks:
  cloudflared_net:
    driver: bridge
    ipam:
     config:
       - subnet: 172.31.0.64/29        
  reverse-proxy:
    external:
      name: reverse-proxy
