version: '3.1'

services:
  portainer:
    image: portainer/portainer
    restart: unless-stopped
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/storage1/docker-persist/portainer:/data
    networks:
      - reverse-proxy
    environment:
      - VIRTUAL_HOST=portainer.wainwright.lan,portainer
      - VIRTUAL_PORT=9000    

networks:
  reverse-proxy:
    external:
      name: reverse-proxy

