version: '3.1'

services:
  homebridge:
    image: homebridge/homebridge:latest
    restart: unless-stopped
    container_name: homebridge
    volumes:
      - /opt/docker-persist/homebridge:/homebridge
    network_mode: host
    environment:
      - VIRTUAL_HOST=homebridge.wainwright.lan,homebridge
      - VIRTUAL_PORT=8581
      - PUID=`id -u`
      - PGID=`id -g`
      - TZ=Europe/London
      - PACKAGES=ffmpeg/openssh
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8581

