services:
  open_webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open_webui
    restart: unless-stopped
    ports:
      - "8081:8080"
    volumes:
      - ${DOCKER_PERSIST}/open_webui:/app/backend/data
    environment:
      - VIRTUAL_HOST=open_webui.internal,open_webui.local,open_webui
      - VIRTUAL_PORT=8081
      - ENABLE_OLLAMA_API=False
      - ENABLE_OPENAI_API=True
      - OPENAI_API_BASE_URLS=${OPENAI_API_BASE_URLS}