version: '3.1'

services:
  syncthing:
    image: syncthing/syncthing
    restart: unless-stopped
    container_name: syncthing
    volumes:
      - /mnt/storage1/docker-persist/syncthing:/var/syncthing/config
      - /mnt/storage1:/var/syncthing/Sync
    networks:
      - reverse-proxy
    environment:
      - VIRTUAL_HOST=syncthing.wainwright.lan,syncthing
      - VIRTUAL_PORT=8384
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.syncthing.rule=Host(`syncthing.wainwright.lan`)"
      - "traefik.http.routers.syncthing.rule=Host(`syncthing`)"
      - "traefik.http.routers.syncthing.entrypoints=web"
      - "traefik.http.services.syncthing.loadbalancer.server.port=8384"
      - "traefik.http.routers.syncthing.service=syncthing"
    ports:
      - 22000:22000
      - 21027:21027/udp

networks:
  reverse-proxy:
    external:
      name: reverse-proxy

