version: '3.1'

services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - NET_BIND_SERVICE
    volumes:
      - /opt/docker-persist/pi-hole/:/etc/pihole/
      - /opt/docker-persist/pi-hole/dnsmasq.d/:/etc/dnsmasq.d/
    environment:
      - VIRTUAL_HOST=pihole.wainwright.lan,pihole
      - DNSMASQ_LISTENING=all
      - TZ=Europe/London
      - WEBPASSWORD=${WEBPASSWD}    
      - PIHOLE_DNS_=127.0.0.1#8053
      - PIHOLE_DOMAIN=wainwright.lan
      - IPv6=false
      - ServerIP=192.168.221.1

  stubby:
    build:
      context: ./DoHttps
      dockerfile: Dockerfile
    container_name: stubby
    restart: unless-stopped
    network_mode: host
    volumes:
      - /opt/docker-persist/stubby/:/config/

