---
version: "2.1"
services:
  speedtest:
    image: adolfintel/speedtest:latest
    container_name: speedtest
    environment:
      - TZ=Etc/UTC
      - PASSWORD=qwerty
      - TITLE=speedtest.wainwright.lan
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.speedtest.rule=Host(`speedtest.wainwright.lan`)"
      - "traefik.http.routers.speedtest.entrypoints=web"
      - "traefik.http.services.speedtest.loadbalancer.server.port=80"
      - "traefik.http.routers.speedtest.service=speedtest"
    networks:
      - reverse-proxy

networks:
  reverse-proxy:
    external: true
