---
version: "3.1"
services:
  snapdrop:
    image: lscr.io/linuxserver/snapdrop:latest
    container_name: snapdrop
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.snapdrop.rule=Host(`snapdrop.wainwright.lan`)
      - traefik.http.routers.snapdrop.rule=Host(`snapdrop`)
      - traefik.http.routers.snapdrop.entrypoints=web
      - traefik.http.services.snapdrop.loadbalancer.server.port=80
      - traefik.http.routers.snapdrop.service=snapdrop
    networks:
      - reverse-proxy

networks:
  reverse-proxy:
    external: true

