version: '3.1'

services:
  autoheal:
      image: willfarrell/autoheal:latest
      tty: true
      restart: always
      environment:
        - AUTOHEAL_INTERVAL=60
        - AUTOHEAL_START_PERIOD=45
        - AUTOHEAL_DEFAULT_STOP_TIMEOUT=10
        - AUTOHEAL_CONTAINER_LABEL=all
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock

